# Generated by Django 4.2.1 on 2023-09-19 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pojistovna_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pojistenec',
            options={'verbose_name': 'Pojištěnec', 'verbose_name_plural': 'Pojištěnci'},
        ),
        migrations.AlterModelOptions(
            name='pojisteni',
            options={'verbose_name': 'Pojištění', 'verbose_name_plural': 'Pojištění'},
        ),
    ]
