# Generated by Django 4.2.1 on 2023-09-09 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pojisteny',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(max_length=200)),
                ('adresa', models.CharField(max_length=200)),
                ('kontakt', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Pojisteni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev_pojisteni', models.CharField(max_length=80)),
                ('pojisteny', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pojisteni.pojisteny')),
            ],
        ),
    ]
