# Generated by Django 4.2.1 on 2023-09-14 09:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pojisteni', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pojisteni',
            name='platnost_do',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='pojisteni',
            name='platnost_od',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
