# Generated by Django 4.2.1 on 2023-09-12 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pojisteni', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pojistenec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(max_length=100)),
                ('prijmeni', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefon', models.CharField(max_length=20)),
                ('ulice_cislo', models.CharField(max_length=100)),
                ('mesto', models.CharField(max_length=100)),
                ('psc', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='pojisteni',
            name='nazev_pojisteni',
        ),
        migrations.RemoveField(
            model_name='pojisteni',
            name='pojisteny',
        ),
        migrations.AddField(
            model_name='pojisteni',
            name='castka',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pojisteni',
            name='platnost_do',
            field=models.DateField(default=0.0),
        ),
        migrations.AddField(
            model_name='pojisteni',
            name='platnost_od',
            field=models.DateField(default=0.0),
        ),
        migrations.AddField(
            model_name='pojisteni',
            name='predmet_pojisteni',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Pojisteny',
        ),
        migrations.AddField(
            model_name='pojistenec',
            name='pojisteni',
            field=models.ManyToManyField(related_name='pojisteni', to='pojisteni.pojisteni'),
        ),
    ]
