# Generated by Django 4.2.1 on 2023-09-12 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pojisteni', '0002_pojistenec_remove_pojisteni_nazev_pojisteni_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pojisteni',
            name='platnost_do',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='pojisteni',
            name='platnost_od',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
