# Generated by Django 4.2.1 on 2023-09-13 08:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pojisteni', '0006_alter_pojisteni_platnost_do_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pojisteni',
            name='platnost_do',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='pojisteni',
            name='platnost_od',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
