# Generated by Django 4.2.1 on 2023-09-13 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pojisteni', '0007_alter_pojisteni_platnost_do_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pojisteni',
            name='platnost_do',
            field=models.DateField(default=''),
        ),
        migrations.AlterField(
            model_name='pojisteni',
            name='platnost_od',
            field=models.DateField(default=''),
        ),
    ]
