# Generated by Django 4.2.1 on 2023-09-14 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pojisteni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('castka', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('predmet_pojisteni', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Pojistenec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(max_length=100)),
                ('prijmeni', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefon', models.CharField(max_length=20)),
                ('ulice_cislo', models.CharField(max_length=100)),
                ('mesto', models.CharField(max_length=100)),
                ('psc', models.CharField(max_length=10)),
                ('pojisteni', models.ManyToManyField(related_name='pojisteni', to='pojisteni.pojisteni')),
            ],
        ),
    ]
